### ISSUE TITLE
EKF2 yaw estimation error 

### ISSUE THREAD

**Issue by totomyl** [PX4/PX4-Autopilot#12541] opened 2019-07-23 13:39 UTC
Hello,

I am trying to send motion capture data to a pixfalcon running px4 autopilot version 1.8.2. The motion capture system (mocap optitrack) is being published to the topic /mavros/vision_pose/pose. I am currently using EKF2 to estimate the position of the drone, I have set EKF2_AID_MASK to 24 (yaw + vision fusion). The barometer is disabled as well as the magnetometer and gps.

When visualizing the data in RVIZ, I am able to see both the mavros/vision_pose/pose and mavros/local_position/pose topics, however, the local_position topic keeps on yawing while the drone is still. When the drone is being moved around, both the local_position and the vision_pose move but the local_pose is constantly yawing so they are never in line.

I have tried upgrading the px4 firmware to 1.9.2 but this did not solve the problem. The sensors were re-calibrated multiple times and that did not help either.

Here is the log https://review.px4.io/plot_app?log=a72dd458-dc4f-4650-8335-02242da6e094
link to download: https://drive.google.com/open?id=16aOQq7O2m_1sBSl38vRLrrPXAQSijeY9

Any help or guidance would be appreciated, thank you in advance!

**Comment by RomanBapst** [comment] 2019-07-23 14:01
@totomyl You will need to provide a log otherwise we can't help you.

**Comment by totomyl** [comment] 2019-07-23 14:33
@RomanBapst sorry about that, I have added the link to the flight review, I was not sure how to put the actual file onto here as it was not supported.

**Comment by artifactz** [comment] 2019-07-29 14:01
Maybe you can take a look at `rostopich echo /mavros/imu/data_raw` to check if the yawing already happens there. Also, your `EKF2_MAG_NOISE` parameter seems very high (`EKF2_EV_GATE` as well).

**Comment by julianoes** [comment] 2019-07-30 13:56
@totomyl is this a duplicate of  #12577 or something else?

**Comment by totomyl** [comment] 2019-07-30 14:54
> @totomyl is this a duplicate of #12577 or something else?

#12577 is a different problem, the mag won't even disable on it

**Comment by bresch** [comment] 2022-08-15 12:50
This was caused by an issue in the gyro bias estimate (due to some numerical issues in the covariance prediction step). It's now fixed on `main` and release 1.13
![DeepinScreenshot_select-area_20220815144942](https://user-images.githubusercontent.com/14822839/184637988-93620a7c-8536-417c-b15a-86afa8e4a5d0.png)

**Closed by bresch** 2022-08-15 12:50 UTC
Labels: state estimation
