### ISSUE TITLE
VTOL will not convert to FW when motors run

### ISSUE THREAD

**Issue by bukovec1** [PX4/PX4-Autopilot#15497] opened 2020-08-05 16:01 UTC
Hello,

All tests were done on the bench. 

We manually set a switch on the transmitter that would allow us to "transition" from MC to FW. We could arm the ship and **without any motors spinning**, I could flip the switch and QGC would show the vehicle would go into FW state. 

Unfortunately, when the motors are spinning and I flip the switch to put the vehicle in FW mode, nothing happens. QGC does not show that the ship is in FW, it just stays constant in MC mode. 

I am wondering if anyone else has had this issue with 1.11.

**Comment by dagar** [comment] 2020-08-05 16:38
Can you share the log (https://logs.px4.io/)? I'm wondering if there's an interaction with the land detector you're seeing.

**Comment by bukovec1** [comment] 2020-08-05 19:10
Hello,

Can you view this file from this url?

https://review.px4.io/plot_app?log=d5c46412-2c4c-4447-83ba-bb668a674d89

**Comment by notoriou5** [comment] 2020-08-06 07:35
@bukovec1 I experienced the same issue, but in the opposite direction. Once the motors where off, I could not do the transition. Did you connect your tilt servos through the AUX Channel? I changed PWM_AUX_DISARMED and PWM_AUX_MIN both to 1000 and it worked again. Not sure whats the reason for that. Hopefully it helps you as well

**Comment by bukovec1** [comment] 2020-08-06 14:35
@notoriou5 

Thanks for your comment. Unfortunately 1.11 does not have  PWM_AUX_DISARMED and PWM_AUX_MIN exactly, but I did try to change both PWM_MIN and PWM_DISARM to 1000 and neither solved my issue yet.

**Comment by xdwgood** [comment] 2020-08-11 08:58
I have same problem.(on two motor tailsitter)

fix by here:
https://github.com/PX4/Firmware/pull/15493
https://github.com/PX4/Firmware/pull/15352

**Comment by bukovec1** [comment] 2020-08-11 13:29
@dagar is this solution valid? I was looking at #15493 and it still looks like it needs approved by someone? 

@xdwgood thank you for this. I will try it to see what happens

**Comment by xdwgood** [comment] 2020-08-12 02:05
@bukovec1  If you tested with #15493 , it would be great to provide feedback

**Comment by bukovec1** [comment] 2020-08-19 19:31
Hello @xdwgood  @dagar @sfuhrer @notoriou5 

I found the issue. It was because the transition airspeed was set to 10 m/s, and since I was inside bench testing, this was not happening. When setting this to 0, I can transition.

**Comment by sfuhrer** [comment] 2020-08-25 13:08
> Hello @xdwgood @dagar @sfuhrer @notoriou5
> 
> I found the issue. It was because the transition airspeed was set to 10 m/s, and since I was inside bench testing, this was not happening. When setting this to 0, I can transition.

Okay, then I guess we can close this issue?
You can also blow briefly into the pitot tube when doing transitions on a bench setup to fake airspeed.

**Comment by xdwgood** [comment] 2020-08-26 00:00
@sfuhrer  As this log shows, the flight transmission failed because there was no pitch setting value, not because the conversion airspeed was not reached.https://github.com/PX4/Firmware/issues/15497#issuecomment-671822763(see picture)

I hope it will be completely resolved, rather than hidden.I am not against closing it, but we should continue to work here:https://github.com/PX4/Firmware/pull/15493

**Comment by sfuhrer** [comment] 2020-08-26 15:46
@xdwgood this log file:

> https://review.px4.io/plot_app?log=d5c46412-2c4c-4447-83ba-bb668a674d89

is from a standard VTOL, and your issue is with a tailsitter right? So I don't think they're related.

**Comment by xdwgood** [comment] 2020-08-27 00:30
@sfuhrer  I remember that `VTOL Quad Tailsitter (13003)` called tailsitter.cpp

`VTOL Quad Tailsitter`  not `standard VTOL`

You can check the code again to verify this

![Screenshot from 2020-08-27 08-29-27](https://user-images.githubusercontent.com/24932258/91369888-7c0c8380-e83f-11ea-80e2-09f158001f0e.png)

vtol_type = 0 means:

![Screenshot from 2020-08-27 08-30-23](https://user-images.githubusercontent.com/24932258/91369925-95153480-e83f-11ea-9e77-1e4edeac20e0.png)

**Comment by yuthikasagarage** [comment] 2020-10-03 06:50
in the tailsitter also, if you blow across the pitot, it transitions to fw. and after the normalization was added --->

https://github.com/PX4/Firmware/blob/8ee0c62e575435f4bb751599ae277bab1208c809/src/modules/vtol_att_control/tailsitter.cpp#L216

i didn't come across any pitch setpoint publishing error.

**Comment by sfuhrer** [comment] 2021-01-18 20:54
Closing as the cause for the original issue was found 
>I found the issue. It was because the transition airspeed was set to 10 m/s, and since I was inside bench testing, this was not happening. When setting this to 0, I can transition.

Please open a new issue if still present on some setups.

**Closed by sfuhrer** 2021-01-18 20:54 UTC
Labels: vtol
