### ISSUE TITLE
CI SITL plane failures

### ISSUE THREAD

**Issue by dagar** [PX4/PX4-Autopilot#16639] opened 2021-01-24 23:24 UTC
SITL plane has been failing lately in CI. https://github.com/PX4/PX4-Autopilot/pull/16635/checks?check_run_id=1758446359

![Screenshot from 2021-01-24 18-22-55](https://user-images.githubusercontent.com/84712/105647011-32b57400-5e71-11eb-84de-e79411249950.png)
![Screenshot from 2021-01-24 18-23-28](https://user-images.githubusercontent.com/84712/105647033-47920780-5e71-11eb-81dd-f7bace6a9c47.png)

**Comment by Jaeyoung-Lim** [comment] 2021-01-25 07:49
Looks like there were some changes in the liftdrag plugin: https://github.com/PX4/PX4-SITL_gazebo/pull/562

**Comment by sfuhrer** [comment] 2021-01-25 09:44
Look to me like an issue in the FW takeoff - manual flying, GOTOs and landings look fine, but 100% reproducible when you start a mission with a takeoff. Probably something pitch setpoint related. 
![image](https://user-images.githubusercontent.com/26798987/105688761-448f2980-5efa-11eb-9854-0b0428942f78.png)

**Comment by mrpollo** [comment] 2021-04-28 15:57
fixed by #16792 

Thanks @sfuhrer

**Comment by mrpollo** [comment] 2021-04-28 15:57
fixed by #16792 

Thanks @sfuhrer

**Closed by mrpollo** 2021-04-28 15:57 UTC
Labels: CI, bug
