### ISSUE TITLE
Unable to build stable Firmware

### ISSUE THREAD

**Issue by JAPolo2** [PX4/PX4-Autopilot#15963] opened 2020-10-14 15:25 UTC
**Describe the bug**
Unable to do calibration on QGC using a custom firmware

**To Reproduce**
1. Clone the PX4 firmware from git using Ubuntu 20.04 (_git clone https://github.com/PX4/Firmware.git --recursive_)
2. Make a clean build (without modifying the code) for getting Cube Orange firmware
3. Flash a Orange Cube with the custom firmware using QGC daily version on Windows 10
4. Try to calibrate sensors. Gyroscope calibration never completes (progress bar still loading); sometimes, compass and airframe don't follow the configured autopilot orientation.
5. Try to arm without success.

**Expected behavior**
To be able to build a stable custom firmware and to be able to calibrate and arm the drone with no problem.

**Log Files and Screenshots**

- When doing a clean build, PX4 version is v1.11.0-rc3 instead of v1.11.1 (latest version of stable release)
![image](https://user-images.githubusercontent.com/69590251/96010223-93afc380-0e0f-11eb-8974-024354f25479.png)

![image](https://user-images.githubusercontent.com/69590251/96010105-6f53e700-0e0f-11eb-82fb-8e1672add6c5.png)

-Incomplete gyroscope calibration
![image](https://user-images.githubusercontent.com/69590251/96009990-4e8b9180-0e0f-11eb-8738-eb68ed832744.png)

**Drone:**
- Custom Y tricopter (1 main front motor with two rear motors)

**Additional context**
- Clean builds were made without any modification in the code.
- The objective of having a custom firmware is to add a new airframe configuration.

**Comment by dagar** [comment] 2020-10-14 15:39
Is there a specific error? Can you reproduce with a log from boot (SDLOG_MODE 2)?

**Comment by JAPolo2** [comment] 2020-10-15 14:02
> Is there a specific error? Can you reproduce with a log from boot (SDLOG_MODE 2)?

Actually, I'm a beginner using PX4 so I don't know exactly how I can get a log from boost...Could you please show me how to do it?
Anyway, I solved the problem by changing the Firmware release version:

`git clone https://github.com/PX4/Firmware.git` (no `--recursive`)
`cd Firmware/`
`git checkout v1.11.1`

After performing a build for Cube orange and flashing the controller with QGC, I get the latest firmware version and I'm able to do the sensor calibration and arming the drone:

![image](https://user-images.githubusercontent.com/69590251/96137675-eac69e80-0eca-11eb-8877-b76d2833ff4b.png)

I don't know if I'm the only one to have that problem, but it's weird that I'm not able to build the code by just cloning the latest firmware version. I mean, if I don't use `git checkout` for choosing v1.11.1, the firmware I build is unstable...

**Comment by julianoes** [comment] 2023-04-03 02:07
Sounds like the problem was solved for OP, so I'll close this.

**Closed by julianoes** 2023-04-03 02:07 UTC
