### ISSUE TITLE
Problem in setup jsbsim SITL with Cygwin in windows

### ISSUE THREAD

**Issue by moreba1** [PX4/PX4-Autopilot#16294] opened 2020-11-28 11:20 UTC
I installed the Cygwin and cloned px4 then installed rolling release of jsbsim on windows.
when i run px4 SITL (HEADLESS=1 make px4_sitl jsbsim_rascal) i get this error:

![1](https://user-images.githubusercontent.com/14200369/100514322-ec050f80-3188-11eb-976d-43f798a7b276.JPG)

![2](https://user-images.githubusercontent.com/14200369/100514327-f6270e00-3188-11eb-8f90-cf85b84414cb.JPG)

**Comment by Jaeyoung-Lim** [comment] 2020-11-28 12:19
Closing since it is a duplicate of https://github.com/Auterion/px4-jsbsim-bridge/issues/41

**Closed by Jaeyoung-Lim** 2020-11-28 12:19 UTC
