### ISSUE TITLE
Holybro Kakute H7, it can't use DShot as ESC protocol

### ISSUE THREAD

**Issue by helloliver** [PX4/PX4-Autopilot#20295] opened 2022-09-23 13:26 UTC
Hello,

I use Holybro Kakute H7. I want to use DShot instead of PWM. But after I config the DShot, the motor cannot spin anyway. Besides, the official doc [dshot-escs](https://docs.px4.io/main/en/peripherals/dshot.html?#dshot-escs) seems help nothing.

Is there way to use DShot as ESC protocol for Holybro Kakute H7?

Thanks.

**Comment by mywisdomfly** [comment] 2022-09-28 14:28
I'm using Kakute H7 (old version MPU6000). Dshot is fine to me.

**Comment by helloliver** [comment] 2022-09-28 14:43
@mywisdomfly I would appreciate it if you can provide the PX4-Autopilot commit ID that you used.

**Comment by mywisdomfly** [comment] 2022-09-28 15:34
I'm using the latest release firmware and QGC.

**Comment by mywisdomfly** [comment] 2022-10-20 09:50
> @mywisdomfly Can you switch into offborad mode with Kakute H7? Thanks!
> 
> > I'm using Kakute H7 (old version MPU6000). Dshot is fine to me.

Yes.

**Comment by julianoes** [comment] 2023-01-06 01:52
I'm going to close this issue as a duplicate of https://github.com/PX4/PX4-Autopilot/issues/20345. I'm aware that this issue was first but the other one has more information.

And fix should be coming in: https://github.com/PX4/PX4-Autopilot/pull/20873

**Closed by julianoes** 2023-01-06 01:52 UTC
Labels: bug-report
