### ISSUE TITLE
[Bug] Quadrotor falls down or escape from mission when velocity or position params is changed

### ISSUE THREAD

**Issue by patric6123** [PX4/PX4-Autopilot#22050] opened 2023-09-06 15:20 UTC
### Describe the bug

When velocity or position params is changed, the quadrotor falls down or escape from mission.
The cases are below,
1. MPC_THR_MAX : 0
2. MPC_XY_P : 0.0001 ( or lower )
3. MPC_XY_P : 10 ( or higher )
4. MPC_XY_P : 2, MPC_XY_VEL_I_ACC : 6
5. MPC_XY_VEL_I_ACC : 46.599998 ( or higher )
6. MPC_XY_VEL_MAX : 0
7. MPC_XY_VEL_P_ACC : 0
8. MPC_XY_VEL_P_ACC : 100
9. MPC_Z_P : 0
10. MPC_Z_P : 100
11. MPC_Z_VEL_MAX_DN : 2.0

### To Reproduce

1. run px4
2. take off ( or start mission )
3. change parameters

### Expected behavior

Fly normally, not fall down or escape from the mission

### Flight Log

.

### Software Version

1.14.0-rc1

### Flight controller

Quadrotor

### Vehicle type

Multicopter

**Comment by dagar** [comment] 2023-09-07 14:55
Duplicate of https://github.com/PX4/PX4-Autopilot/issues/22052

**Closed by dagar** 2023-09-07 14:55 UTC
Labels: bug-report
