### ISSUE TITLE
[Bug] some angular & angular rate parameter value is changed, a flight falls down or flies wrong.

### ISSUE THREAD

**Issue by patric6123** [PX4/PX4-Autopilot#22046] opened 2023-09-05 15:39 UTC
### Describe the bug

Some angular & angular rate parameters' value is changed, a flight falls down or flies wrong.
1. MC_PITCHRATE_D : 0.05
2. MC_PITCHRATE_FF : 0.8
3. MC_PITCHRATE_K : 4.0 and MC_PITCHRATE_P : 0.45( or higher )
4. MC_ROLL_P : 0.1( or lower )
5. MC_ROLLRATE_K : 0.01
6. MC_ROLLRATE_K : 5.0
7. MC_ROLLRATE_MAX : 0.0
8. MC_ROLLRATE_P : 0.03 ( or lower )
9. MC_ROLLRATE_P : 0.5
10. MC_YAW_P : 100.0 ( or higher )
11. MC_YAW_P : 17.9 and MC_YAWRATE_FF : 1.8
12. MC_YAWRATE_FF : 10
13. MC_YAWRATE_P : 0

### To Reproduce

1. run px4
2. take off
3. set parameter one of them ( above )

### Expected behavior

not fall down or fly wrong

### Flight Log

.

### Software Version

1.14.0-rc1

### Flight controller

Quadrotor

### Vehicle type

Multicopter

**Comment by dagar** [comment] 2023-09-07 14:55
Duplicate of https://github.com/PX4/PX4-Autopilot/issues/22052

**Closed by dagar** 2023-09-07 14:55 UTC
Labels: bug-report
